export const SET_LoginFormOpen = "SET_LoginFormOpen";
export const SET_SignupFormOpen = "SET_SignupFormOpen";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";

export const SET_CREATE_BUISNESS_PAGE = "SET_CREATE_BUISNESS_PAGE";
export const SET_SECOND_CREATE_BUISNESS_PAGE =
  "SET_SECOND_CREATE_BUISNESS_PAGE";
export const SET_THIRD_CREATE_BUISNESS_PAGE = "SET_THIRD_CREATE_BUISNESS_PAGE";
export const SET_FOURTH_CREATE_BUISNESS_PAGE =
  "SET_FOURTH_CREATE_BUISNESS_PAGE";
export const SET_SUCESS_PAGE = "SET_SUCESS_PAGE";

export const SET_BUISNESS_NAME = "SET_BUISNESS_NAME";
export const SET_PINCODE = "SET_PINCODE";
export const SET_AREA = "SET_AREA";
export const SET_STREET = "SET_STREET";
export const SET_BUILDING_NAME = "SET_BUILDING_NAME";
export const SET_CITY = "SET_CITY";
export const SET_STATE = "SET_STATE";
export const SET_CONTACT_PERSON = "SET_CONTACT_PERSON";
export const SET_PHONE = "SET_PHONE";
export const SET_CONTACT_EMAIL = "SET_CONTACT_EMAIL";
export const SET_ADHAAR = "SET_ADHAAR";

export const SET_DAYS_OPEN = "SET_DAYS_OPEN";
export const SET_OPEN_AT = "SET_OPEN_AT";
export const SET_CLOSE_AT = "SET_CLOSE_AT";

export const SET_CATEGORY = "SET_CATEGORY";

export const SET_SEARCH_CATEGORY = "SET_SEARCH_CATEGORY";
export const SET_SEARCH_LOCATION = "SET_SEARCH_LOCATION";

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

