# Generated by Django 5.1.2 on 2024-11-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quickserve.address'),
        ),
    ]
