# Generated by Django 5.1.1 on 2024-11-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickserve', '0002_service_available_all_hours_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysavailable',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quickserve.service'),
        ),
    ]
