# Generated by Django 5.1.2 on 2024-11-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickserve', '0002_alter_service_address'),
        ('quickserve', '0002_service_available_all_hours_service_id_and_more'),
    ]

    operations = [
    ]
