# Generated by Django 5.1.1 on 2024-11-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickserve', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
