# Generated by Django 5.1.1 on 2024-11-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickserve', '0006_alter_daysavailable_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysavailable',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daysavailable',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daysavailable', to='quickserve.service'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickserve.service'),
        ),
    ]
